#!/bin/bash

sudo apt update && sudo apt upgrade
sudo apt install gcc gnupg2

gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

cd ~
curl -sSL https://get.rvm.io | bash -s stable
source ~/.rvm/scripts/rvm

rvm install 3.0.2


apt-get install -y mysql-client libmysqlclient-dev

cd ~/db-syncing

bundle install

apt install nodejs npm -y
sudo npm install --global yarn
bundle exec rake webpacker:install



